id = "grimaces-birthday"
name = "Grimace's Birthday"
version = "0.1.0"
schema_version = 1
authors = ["ssaunderss <austinsaunders@me.com>"]
description = "Theme to help you celebrate Grimace's Birthday."
repository = "https://github.com/ssaunderss/grimaces-birthday"
